---
title: "Downloading Precip Data in Colorado"
author: "Keian Freshwater"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
editor_options: 
  chunk_output_type: console
---


# Precipitation Data Download


```{r download-packages, include=FALSE}
library(riem)
library(sf)
library(mapview)
library(tidyverse)
library(rayshader)
library(USAboundaries)
library(raster)
library(elevatr)
library(tmap)

knitr::opts_chunk$set(echo = TRUE)
```

# Download and data check


```{r, message=F, warning=F}
network <- riem_networks()

co_stations <- riem_stations(network = 'CO_ASOS') %>%
  st_as_sf(., coords = c('lon','lat'), crs = 4326)
glimpse(co_stations)
```

## Interactive map

```{r, message=F, warning=F}
mapview(co_stations)
```


## Static map


### Download some state boundary data


```{r,message=F, warning=F}
co <- us_counties(
                  states = 'Colorado')
co_elev <- elevatr::get_elev_raster(co_stations,
                                  z = 9 )
```

```{r, message=F, warning=F}
tm_shape(co) + 
  tm_polygons(col = 'white') + 
tm_shape(co_stations) + 
  tm_bubbles(size = 0.2) 
```

# Download a single site data
```{r, message=F, warning=F}
fnl <- riem_measures(station = 'FNL', 
                     date_start = '1987-05-01',
                     date_end = '1992-11-01')

daily_fnl <- fnl %>%
  mutate(date = as.Date(valid)) %>%
  group_by(date) %>%
  summarize(daily_rain = mean(tmpf,na.rm=T))

ggplot(daily_fnl, aes(x=date, y=daily_rain)) +
  geom_point()+
  scale_y_log10()+
  xlab('Date') +
  ylab('Daily Precipitation, Fort Collins')
```


# Compare to a second site data
```{r, message=F, warning=F}
gjt <- riem_measures(station = 'GJT', 
                     date_start = '1987-05-01',
                     date_end = '1992-11-01')

daily_gjt <- gjt %>%
  mutate(date = as.Date(valid)) %>%
  group_by(date) %>%
  summarize(daily_rain = mean(tmpf,na.rm=T))

ggplot(daily_gjt, aes(x=date, y=daily_rain)) +
  geom_point()+
  scale_y_log10()+
  ylab('Daily Precipitation, Grand Junction')
```

# Compare to a third site data

```{r, message=F, warning=F}
lxv <- riem_measures(station = 'LXV', 
                     date_start = '1987-05-01',
                     date_end = '1992-11-01')

daily_lxv <- lxv %>%
  mutate(date = as.Date(valid)) %>%
  group_by(date) %>%
  summarize(daily_rain = mean(tmpf,na.rm=T))

ggplot(daily_lxv, aes(x=date, y=daily_rain)) +
  geom_point()+
  scale_y_log10() +
  xlab('Date') +
  ylab('Daily Precipitation, Leadville')
```

# Compare on same graph

```{r, message=F, warning=F}
ggplot() +
  geom_point(data=daily_gjt, aes(x=date, y=daily_rain, color='Grand Junction'))+
  geom_point(data=daily_fnl, aes(x=date, y=daily_rain,color='Fort Collins'))+
  geom_point(data=daily_lxv, aes(x=date, y=daily_rain,color='Leadville'))+
  scale_y_log10() +
  xlab('Date')+
  ylab('Daily Precipitation')
```
